[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["openweathermap_report_to_email"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/ManualTrigger","Category/Integration"]
  name = "openweathermap_report_to_email"
  org = "aiteam"
  version = "3.1.0"

